"""Add restaurants_customers association table

Revision ID: 36301a53489e
Revises: 0466008d233c
Create Date: 2023-12-10 03:21:12.614668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36301a53489e'
down_revision = '0466008d233c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants_customers',
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurants_customers')
    # ### end Alembic commands ###
